services:
  mirror_elf_r:
    network_mode: host
    build: ./app
    container_name: mirror_elf_r
    depends_on:
      - minio # 依赖 MinIO 服务
    # restart: unless-stopped # 容器自动重启策略
    volumes:
      - ./app:/app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API 端口
      - "9001:9001" # 控制台端口
    network_mode: host # 使用 host 网络模式
    restart: always # 容器自动重启策略
    environment:
      MINIO_ACCESS_KEY: minio # 访问密钥
      MINIO_SECRET_KEY: minio123 # 秘密密钥
    volumes:
      - ./minio/data:/data # 数据存储目录
      - ./minio/config:/root/.minio # 配置文件目录
    command: server /data --console-address ":9001" -address ":9000" # 启动命令
