ProgramInfo:
  program_name: web1 - Mirror-Elf by TG@seo898
  authorization_code: lvZyfIaojUGpZMSktgtJv6auJ04zyCg4I2K3Zqk6uOpUkbA4RQ5sC9YHjliPSRKQjpCWkAFB0lVIboV5isLV0-4I8K1x
  login_account: admin
  login_password: admin
  amazon_s3_api: minio:minio123@localhost:9000
  pg_database_url: postgresql://admin:mirrorelf@localhost:5432/mirror
WebsiteSettings:
  auto_site_building: false
  auto_https_certificate: true
  pan_site_auto_site_building: true
  pan_site_crawler_target: true
  language: zh
  link_mapping: true
  homepage_update_time: 3
  target_static_save: ''
SEOFunctions:
  external_link_strategy: '6'
  random_meta_and_link: false
  random_class_attributes: false
AccessPolicy:
  forced_domain_binding: false
  ip_site_referrer: true
  pan_site_referrer: true
  ua_banlist:
  - Scrapy
  - Curl
  - HttpClient
  - UniversalFeedParser
  - lightDeckReports Bot
  - heritrix
  - Java
  - Bytespider
  - YandexBot
  - FlightDeckReports
  - Indy Library
  - BOT/0.1
  - DigExt
  - Feedly
  - Swiftbot
  - oBot
  - Python-urllib
  - CrawlDaddy
  - YYSpider
  - JikeSpider
  - ZmEu
  - MJ12bot
  - WebZIP
  - Apache-HttpAsyncClient
  - HttpClient
  - WinHttp
  - jaunty
  - Alexa Toolbar
  - LinkpadBot
  - Microsoft URL Control
  - node-superagent
  - Ezooms
  - Jullo
  - SemrushBot
  - FetchURL
  - AhrefsBot
  - EasouSpider
  - java/
  - CoolpadWebkit
  - Linguee Bot
  ip_banlist: []
AdPolicy:
  ad_url: http://www.baidu.com
  search_referrer_jump_ad: false
  regular_ua_jump_ad: false
GlobalCodeInsertion:
  filter_ip:
  - 156.59.82.139
  head_header: <script src="/_/static/js/tongji.js" type="text/javascript"></script><script src="/_/static/js/ad.js" type="text/javascript"></script>
  head_footer: ''
  body_header: ''
  body_footer: ''
SpiderPolicy:
  baidu_spider: true
  sogou_spider: true
  yisou_spider: true
  byte_spider: true
  bing_spider: true
  so_spider: true
  google_img_spider: true
  google_spider: true
  quark_spider: true
  yahoo_spider: true
  other_spider: true
  user: true
