WebsiteInfo:
  program_name: web1 - Mirror-Elf by TG@seo898
  authorization_code: '888'
  login_account: admin
  login_password: admin
  amazon_s3_api: minio:minio123@localhost:9000
  safeline_token: ''
WebsiteSettings:
  auto_site_building: true
  auto_https_certificate: true
  pan_site_auto_site_building: true
  pan_site_crawler_target: true
  language: zh
  homepage_update_time: 4
  link_mapping: true
SEOFunctions:
  external_link_strategy: '3'
  random_meta_and_link: false
  random_class_attributes: false
AccessPolicy:
  forced_domain_binding: true
  ip_site_referrer: false
  pan_site_referrer: true
  ua_banlist:
  - Scrapy
  - Curl
  - HttpClient
  - UniversalFeedParser
  - lightDeckReports Bot
  - heritrix
  - Java
  - Bytespider
  - YandexBot
  - FlightDeckReports
  - Indy Library
  - BOT/0.1
  - DigExt
  - Feedly
  - Swiftbot
  - oBot
  - Python-urllib
  - CrawlDaddy
  - YYSpider
  - JikeSpider
  - ZmEu
  - MJ12bot
  - WebZIP
  - Apache-HttpAsyncClient
  - HttpClient
  - WinHttp
  - jaunty
  - Alexa Toolbar
  - LinkpadBot
  - Microsoft URL Control
  - node-superagent
  - Ezooms
  - Jullo
  - SemrushBot
  - FetchURL
  - AhrefsBot
  - EasouSpider
  - java/
  - CoolpadWebkit
  - Linguee Bot
  - ApacheBench
  - AskTbFXTV
  - FeedDemon
  ip_banlist:
  - 1.1.1.1
AdPolicy:
  ad_url: http://www.baidu.com
  search_referrer_jump_ad: false
  regular_ua_jump_ad: false
GlobalCodeInsertion:
  filter_ip:
  - 192.168.1.1
  - 168.0.0.1
  head_header: ''
  head_footer: <script src="/_/static/js/ad.js" type="text/javascript"></script>
  body_header: ''
  body_footer: <script src="/_/static/js/tongji.js" type="text/javascript"></script>
SpiderPolicy:
  google_spider: true
  baidu_spider: true
  bing_spider: true
