WebsiteInfo:
  program_name: 'web1 - Mirror-Elf by TG@seo898'
  authorization_code: ''
  login_account: 'admin'
  login_password: 'admin'
  amazon_s3_api: "minio:minio123@localhost:9000"
  safeline_token: ''

WebsiteSettings:
  auto_site_building: True # 自动生成网站配置
  auto_https_certificate: True # 自动生成部署https证书
  pan_site_auto_site_building: True # 自动生成泛站配置
  pan_site_crawler_target: True # 泛站爬虫目标
  language: 'zh' # zh:中文 | zh-Hant:繁体中文 | en:英文 | pt:葡萄牙文
  homepage_update_time: 1 # 单位：天 如果想永不更新首页，填写99999即可
  link_mapping: True # 链接映射

SEOFunctions:
  external_link_strategy: '0' # 0:不处理 | 1:转为本站内部链接 | 2:转为全站随机链接（主站+泛站） | 3:转为链轮链接（服务器上所有站点）
  random_meta_and_link: False # 随机meta&link
  random_class_attributes: False # 随机class属性

AccessPolicy:
  forced_domain_binding: False # 强制域名绑定
  ip_site_referrer: False # IP来路
  pan_site_referrer: True # 泛站来路
  ua_banlist: ["Scrapy", "Curl", "HttpClient", "UniversalFeedParser", "lightDeckReports Bot", "heritrix", "Java", "Bytespider", "YandexBot", "FlightDeckReports", "Indy Library", "BOT/0.1", "DigExt", "Feedly", "Swiftbot", "oBot", "Python-urllib", "CrawlDaddy", "YYSpider", "JikeSpider", "ZmEu", "MJ12bot", "WebZIP", "Apache-HttpAsyncClient", "HttpClient", "WinHttp", "jaunty", "Alexa Toolbar", "LinkpadBot", "Microsoft URL Control", "node-superagent", "Ezooms", "Jullo", "SemrushBot", "FetchURL", "AhrefsBot", "EasouSpider", "java/", "CoolpadWebkit", "Linguee Bot", "ApacheBench", "AskTbFXTV", "FeedDemon"]
  ip_banlist: ['888.888.888.888','88.8.8.8']

AdPolicy:
  ad_url: "<url id=\"cuq48fu4bbjj8n8g45ug\" type=\"url\" status=\"parsed\" title=\"百度一下，你就知道\" wc=\"1190\">http://www.baidu.com</url> "
  search_referrer_jump_ad: False # 搜索来路跳广告
  regular_ua_jump_ad: False # 普通UA头跳广告

GlobalCodeInsertion: # 一般用于插入网站统计和JS广告 过滤IP填写本地IP可过滤掉插入的广告
  filter_ip: ['192.168.1.1','168.0.0.1']
  head_header: ''
  head_footer: '<script src="/_/static/js/ad.js" type="text/javascript"></script>'
  body_header: ''
  body_footer: '<script src="/_/static/js/tongji.js" type="text/javascript"></script>'

SpiderPolicy:
  google_spider: True
  baidu_spider: True
  bing_spider: True